-- 0004_fix_remote_0001_drift.sql
--
-- NEUTERED 2026-08-26. This file intentionally contains no statements. See ADR-024.
--
-- ============================================================================
-- Read this before "restoring" the statements below into something runnable.
-- ============================================================================
--
-- What this migration used to do:
--
--   ALTER TABLE snapshots ADD COLUMN ask_depth_1pct   REAL;
--   ALTER TABLE snapshots ADD COLUMN bid_depth_1pct   REAL;
--   ALTER TABLE snapshots ADD COLUMN ask_depth_5pct   REAL;
--   ALTER TABLE snapshots ADD COLUMN bid_depth_5pct   REAL;
--   ALTER TABLE snapshots ADD COLUMN ask_max_wall     REAL;
--   ALTER TABLE snapshots ADD COLUMN bid_max_wall     REAL;
--   ALTER TABLE snapshots ADD COLUMN ask_order_count  REAL;
--   ALTER TABLE snapshots ADD COLUMN bid_order_count  REAL;
--   ALTER TABLE hourly    ADD COLUMN last_tick_ts INTEGER NOT NULL DEFAULT 0;
--
-- Why it existed: `0001_initial.sql` was edited in place after it had already been
-- applied to the REMOTE database (commit a88c1d2 applied remotely 2026-08-24 08:00:42,
-- then commit 5ab7298 added depth columns to the same file's snapshots CREATE TABLE).
-- Remote's `d1_migrations` had only ever recorded the pre-edit 0001, so remote's real
-- schema was missing those columns and 0002's DROP COLUMN statements failed there. This
-- migration repaired that one database.
--
-- Why it is now empty: the repair was for a specific historical state of ONE database,
-- and it is long since applied there. On any *clean* database the statements above are
-- not merely redundant, they are fatal — `0002` already adds every one of these columns,
-- so a fresh chain died on `duplicate column name: ask_depth_1pct` at this file. That
-- made the entire migration set unreplayable: no preview environment, no second dev
-- machine, no disaster recovery, and ROADMAP Phase 6's "CI runs migrations then deploys"
-- could never have worked.
--
-- Verified before neutering (2026-08-26): a fresh database running 0001 -> 0002 -> 0003
-- -> 0006, skipping this file and 0005 entirely, produces a schema byte-identical to
-- production across all six application tables. These statements add nothing.
--
-- Safe for already-migrated databases because D1's bookkeeping is name-based, not
-- content-hashed: `d1_migrations` is (id, name UNIQUE, applied_at). Remote recorded this
-- filename on 2026-08-25 and will never re-read it.
--
-- Do not delete this file or renumber it. Its NAME is load-bearing — removing it would
-- make wrangler try to apply 0005 and 0006 against a bookkeeping table that expects this
-- entry, and every already-migrated database would disagree with the repo.

SELECT 1;
