-- 0005_fix_remote_0001_drift_products_runs.sql
--
-- NEUTERED 2026-08-26. This file intentionally contains no statements. See ADR-024.
--
-- ============================================================================
-- Read this before "restoring" the statements below into something runnable.
-- ============================================================================
--
-- What this migration used to do:
--
--   ALTER TABLE products ADD COLUMN tier TEXT NOT NULL DEFAULT 'B';
--   CREATE INDEX idx_products_tier ON products (tier);
--   ALTER TABLE runs ADD COLUMN rows_deleted INTEGER;
--   ALTER TABLE runs ADD COLUMN db_size_bytes INTEGER;
--
-- Same cause as 0004: the in-place edit of an already-applied `0001_initial.sql` left the
-- REMOTE database without columns the repo assumed existed. 0004 repaired `snapshots` and
-- `hourly`; this file repaired `products` and `runs`.
--
-- Why it is now empty: the current `0001_initial.sql` already creates `products.tier`,
-- `runs.rows_deleted` and `runs.db_size_bytes` directly in its CREATE TABLE statements.
-- On a clean database these ALTERs fail with `duplicate column name`, which is what broke
-- replay of the whole migration chain. See 0004's header for the full reasoning and the
-- verification that a fresh 0001 -> 0002 -> 0003 -> 0006 run reproduces production's
-- schema exactly.
--
-- Nothing is lost by emptying this file, including `idx_products_tier`: `0001_initial.sql`
-- creates that index itself (line 20), so a fresh replay still produces it. Verified by
-- listing indexes on a from-scratch database — see 0007, which reconciles the index set
-- that genuinely did diverge.
--
-- Do not delete this file or renumber it. Its NAME is load-bearing; see 0004.

SELECT 1;
